version: 0.0
os: linux

files:
  - source: / # Menandakan root directory dari deployment bundle
    destination: /tmp/codedeploy-app # Direktori sementara di EC2 tempat file akan di-copy jika ada

permissions:
  - object: /tmp/codedeploy-app/scripts/stop_and_remove_container.sh
    pattern: "**" 
    owner: root
    group: root
    mode: 755 
    type:
      - file
  - object: /tmp/codedeploy-app/scripts/pull_docker_image.sh
    pattern: "**"
    owner: root
    group: root
    mode: 755
    type:
      - file
  - object: /tmp/codedeploy-app/scripts/start_docker_container.sh
    pattern: "**"
    owner: root
    group: root
    mode: 755
    type:
      - file

hooks:
  BeforeInstall:
    - location: scripts/stop_and_remove_container.sh
      timeout: 60
      runas: root

  AfterInstall:
    - location: scripts/pull_docker_image.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_docker_container.sh
      timeout: 120
      runas: root
