version: 0.0 
os: linux 

files:
  - source: 
    destination: /tmp/codedeploy-app 

hooks:
  BeforeInstall:
    - location: scripts/stop_and_remove_container.sh 
      timeout: 60 
      runas: root 

  AfterInstall:
    - location: scripts/pull_docker_image.sh
      timeout: 300 
      runas: root

  ApplicationStart:
    - location: scripts/start_docker_container.sh
      timeout: 120 
      runas: root
