version: 0.0 # Versi format AppSpec file
os: linux # Sistem operasi target deployment

files:
  - source: / 
    destination: /tmp/codedeploy-app 

permissions:
  - object: /tmp/codedeploy-app/scripts/deploy_container.sh 
    pattern: "**" 
    owner: root
    group: root
    mode: 755 # rwxr-xr-x (executable for owner, readable/executable for group/others)
    type:
      - file

hooks:
  ApplicationStart: 
    - location: scripts/deploy_container.sh 
      timeout: 360 
      runas: root
