name: Deploy Backend to AWS EC2

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKER_PASSWORD }} 

      - name: Build and push Docker image for AMD64
        uses: docker/build-push-action@v5
        with:
          context: ./server 
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/genz-bridge-backend:latest 
          platforms: linux/amd64 

      - name: Deploy to AWS EC2 VM via SSH
        uses: appleboy/ssh-action@master 
        with:
          host: ${{ secrets.SSH_HOST }} 
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          script: |
            echo "Pulling latest Docker image..."
            docker pull ${{ secrets.DOCKER_USERNAME }}/genz-bridge-backend:latest || true 
            
            echo "Stopping and removing old container if exists..."
            docker stop genz-backend || true 
            docker rm genz-backend || true   
            
            echo "Starting new container..."
            docker run -d \
              --name genz-backend \
              --restart always \
              -p 5001:5001 \
              -e DATABASE_URL="${{ secrets.SUPABASE_DATABASE_URL }}" \
              -e OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}" \
              -e PORT=5001 \
              ${{ secrets.DOCKER_USERNAME }}/genz-bridge-backend:latest
            
            echo "Deployment complete."