name: Deploy Backend with AWS CodeDeploy

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2 

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2


      - name: Build and push Docker image to ECR
        uses: docker/build-push-action@v5
        with:
          context: ./server 
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/genz-bridge-backend:latest
          platforms: linux/amd64 
      
      - name: Create Deployment Artifact (Zip)
        run: |
          # Pastikan Anda berada di root directory project Anda
          # (GitHub Actions akan checkout code Anda di sini)
          
          # Pindah ke direktori server (backend)
          cd server
          
          # Buat file zip dari semua yang dibutuhkan CodeDeploy
          zip -r deployment_artifact.zip . -x "node_modules/*" ".git/*" "*.env*" "dist/*" "build/*" "coverage/*" # Exclude unnecessary files
          
          echo "Deployment artifact created: deployment_artifact.zip"

      - name: Upload Deployment Artifact to S3
        run: |
          aws s3 cp server/deployment_artifact.zip s3://genz-bridge-codedeploy-artifacts/deployment_artifact_${{ github.sha }}.zip
          echo "S3_BUCKET_NAME=genz-bridge-codedeploy-artifacts" >> $GITHUB_ENV
          echo "S3_KEY=deployment_artifact_${{ github.sha }}.zip" >> $GITHUB_ENV

      - name: Trigger AWS CodeDeploy Deployment
        run: |
          # Perintah AWS CLI untuk membuat deployment, sekarang menunjuk ke S3
          aws deploy create-deployment \
            --application-name GenZBridgeBackend \
            --deployment-group-name GenZBridgeProdGroup \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --description "Automated deployment from GitHub Actions - ${{ github.sha }}" \
            --revision "revisionType=S3,s3Location={bucket=${{ env.S3_BUCKET_NAME }},key=${{ env.S3_KEY }},bundleType=zip}" \
            --file-exists-behavior OVERWRITE